version: "3.9"
services:
  mongo:
    container_name: milk-backend-mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - milk-backend-mongo:/data/db
    ports:
      - 27017:27017
    restart: on-failure
    command: mongod
volumes:
  milk-backend-mongo:
